### ISSUE TITLE
TestFlight expired

### ISSUE THREAD

**Issue by NextdoorPsycho** [atrinh0/buttoncraft#2]
The TestFlight invitation seems to have expired if you could renew that, that would be fantastic

**Comment by atrinh0** [comment]
Thanks for reporting, updated now (valid for another 90 days).

<img width="697" alt="Screenshot 2022-04-25 at 12 58 24" src="https://user-images.githubusercontent.com/16542463/165084764-b04cf7b4-2a0f-44cb-a700-60859f634265.png">
